/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
NetBeans carrea
 */
package gui;

import modelo.*;
import gui.LogroCard;
import java.awt.*;

public class PanelLogros extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogros
     */
    public PanelLogros(Usuario usuario) {
        initComponents();
     //Este layout es clave para que se vean los fighiodaptas vainas de los logros. 2 filas 4 col, es el grid
    setLayout(new GridLayout(2, 4, 20, 20));
    
    //Toca ponerle los apodos creativos según el día de racha. El int que se pasa como parámetro es el día al que se desbloquea la racha.
    //Para mas info de este array remítase a la clase LogroCard
    LogroCard[] logros = new LogroCard[] {
        new LogroCard("gui/img/logro1.png", "gui/img/logro0.png", 1, "Lector iniciado"),
        new LogroCard("gui/img/logro2.png", "gui/img/logro0.png", 3, "Degustador de libros"),
        new LogroCard("gui/img/logro3.png", "gui/img/logro0.png", 5, "Mini ratón de biblioteca"),
        new LogroCard("gui/img/logro4.png", "gui/img/logro0.png", 7, "La cabra lectora"),
        new LogroCard("gui/img/logro5.png", "gui/img/logro0.png", 10, "Comprometido empedernido"),
        new LogroCard("gui/img/logro6.png", "gui/img/logro0.png", 14, "Nuevo talento lector"),
        new LogroCard("gui/img/logro7.png", "gui/img/logro0.png", 21, "Esquibidi toillet"),
        new LogroCard("gui/img/logro8.png", "gui/img/logro0.png", 30, "Ratón de biblioteca")
    };

    for (LogroCard logro : logros) {
        logro.actualizar(usuario.getRacha().getDiasConsecutivos());
        add(logro);
    }

    revalidate();
    repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
